### ISSUE TITLE
Docker images can't  run com.rabbitmq.perf.PerfTestMulti due to missing java.beans.IntrospectionException

### ISSUE THREAD

**Issue by liuyongqing1** [rabbitmq/rabbitmq-perf-test#135] opened 2019-02-22 07:07 UTC
When I use the docker image pivotalrabbitmq/perf-test:latest to execute the command when running the html project ./bin/runjava com.rabbitmq.perf.PerfTestMulti publish-consume-spec.js publish-consume-result.js
Report the following error
Exception in thread "main" java.lang.NoClassDefFoundError: java/beans/IntrospectionException
When I switch to openjdk 1.8, I can run it.

**Comment by michaelklishin** [comment] 2019-02-22 08:09
[java.beans.IntrospectionException is available](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/java/beans/IntrospectionException.html) in JDK 11 but in the desktop module. I suspect it is missing in the image.

**Comment by acogoluegnes** [comment] 2019-02-22 08:28
Yes, `PerfTestMulti` uses some Java Beans classes. Those are not available in the latest Docker image because the JVM is tailored with `jlink` to include only the required modules. I think using plain reflective calls would do the job, because including the desktop modules would make the Docker image bigger and seems overkill here (PerfTest doesn't need Swing).

**Comment by liuyongqing1** [comment] 2019-02-22 08:32
We use rabbitmq-ha in kubernetes. So the docker image is used for testing, which is convenient for performance testing.

**Comment by michaelklishin** [comment] 2019-02-22 09:49
@liuyongqing1 we recognize that some prefer using the image. This is a reasonable and specific request 👍

**Comment by acogoluegnes** [comment] 2019-02-25 14:53
To reproduce:

```
echo "[{'name': 'consume', 'type': 'simple', 'params':[{'time-limit': 5, 'producer-count': 1, 'consumer-count': 1}]}]" > publish-consume-spec.js 
docker run -it --rm --network host -v $(pwd)/publish-consume-spec.js:/perf_test/publish-consume-spec.js --entrypoint "bin/runjava" pivotalrabbitmq/perf-test:latest com.rabbitmq.perf.PerfTestMulti publish-consume-spec.js output-json-file.js
```

**Comment by acogoluegnes** [comment] 2019-02-28 09:31
Fixed by #138.

**Closed by acogoluegnes** 2019-02-28 09:31 UTC
Labels: bug, usability

**Comment by acogoluegnes** [comment] 2019-03-08 14:08
@liuyongqing1 [2.7.0.RC1](https://groups.google.com/d/msg/rabbitmq-users/jwZP5kft3_E/_gOA84HPAAAJ) fixes the issue, you can give a try to the latest Docker image.

**Comment by liuyongqing1** [comment] 2019-03-14 02:01
@acogoluegnes ok thanks
